AkHash
AkHash
AkHash()
template<typename TAlloc , typename T_CHAR > static AkForceInline AkUInt32 AkHash (const AkString< TAlloc, T_CHAR > & in_str) static
Definition at line 260 of file AkString.h.
References AK::FNVHash< HashParams >::Compute(), and AkString< TAlloc, T_CHAR >::Get().
Referenced by AkDbString< TAlloc, T_CHAR, tLock >::Aquire().