AkSubtraction
AkContains
AkCountIntersection
AkDisjoint
AkIntersect
AkIntersect
AkIntersection
AkIntersection
AkIsSubset
AkSetType
AkSubtraction
AkSubtraction
AkUnion
AkUnion
AkUniqueIDSet
AkSubtraction() [2/2]
template<typename T , class U_POOL , class uGrowBy , class TMovePolicy , class TComparePolicy > static bool AkSubtraction (AkSet< T, U_POOL, uGrowBy, TMovePolicy, TComparePolicy > & in_A, const AkSet< T, U_POOL, uGrowBy, TMovePolicy, TComparePolicy > & in_B) static
Definition at line 146 of file AkSet.h.
References AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::Begin(), AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::End(), and AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::Resize().
Referenced by AkSubtraction(), and AkUnion().