AK_PLUGIN_DELETE
AK_PLUGIN_ALLOC
AK_PLUGIN_ALLOC_ALIGN
AK_PLUGIN_DELETE
AK_PLUGIN_FREE
AK_PLUGIN_NEW
AK_PLUGIN_REALLOC
AK_PLUGIN_REALLOC_ALIGN
operator delete
operator delete
operator new
operator new
AK_PLUGIN_DELETE()
template<class T > AkForceInline void AK_PLUGIN_DELETE (AK::IAkPluginMemAlloc * in_pAllocator, T * in_pObject)
Macro used to delete objects.
Parameters
in_pAllocator Memory allocator interface.
in_pObject A pointer to the allocated object.
See also
Allocating/De-allocating Memory in Audio Plug-ins
AK_PLUGIN_NEW()
Definition at line 179 of file IAkPluginMemAlloc.h.
References AK::IAkPluginMemAlloc::Free().
Referenced by AkMixerInputMap< KEY, USER_DATA >::EraseSwap(), AkMixerInputMap< KEY, USER_DATA >::RemoveAll(), and AkMixerInputMap< KEY, USER_DATA >::RemoveInput().