AkPlane::FindIntersectionPoints
AkPlane
AkPlane
DistPoint_to_Plane
DoesRayIntersect
FindIntersectionPoints
GetD
GetN
GetP1
GetP2
GetP4
SetPlane
SetReflection
FindIntersectionPoints()
bool AkPlane::FindIntersectionPoints (const AkPlane & in_PlaneB, AkIntersectionPoints & out_Intrs) const inline
Definition at line 1559 of file AkVectors.h.
References AKASSERT, AkMax, AkMin, AKVECTORS_EPSILON, AkIntersectionPoints::count, T3DVector< TDataType >::Cross(), GetD(), GetN(), GetP1(), GetP2(), GetP4(), AkLine::Intersect(), T3DVector< TDataType >::Length(), AkLine::maxt, AkLine::mint, T3DVector< TDataType >::Normalize(), AKPLATFORM::OutputDebugMsg(), AkLine::PointAt(), AkIntersectionPoints::points, T3DVector< TDataType >::X, T3DVector< TDataType >::Y, and T3DVector< TDataType >::Z.