AkSafeConversion::Convert
Convert
Convert
Convert() [1/2]
AkForceInline void AkSafeConversion::Convert (AkReal64 & out_to, AkReal32 in_from) inline
Definition at line 195 of file AkVectors.h.
Referenced by T3DVector< TReal >::operator AkVector(), T3DVector< TReal >::operator AkVector64(), and T3DVector< TReal >::T3DVector().