AkSortedKeyArray::Lesser
Add
AddNoSetKey
AddNoSetKey
base
BinarySearch
Equal
Exists
Iterator
Lesser
LowerBounds
LowerBounds
Reorder
ReSortArray
Set
Set
Swap
Unset
Lesser()
template<class T_KEY , class T_ITEM , class U_POOL = ArrayPoolDefault, class U_KEY = AkGetArrayKey< T_KEY, T_ITEM >, class TGrowBy = AkGrowByPolicy_DEFAULT, class TMovePolicy = AkAssignmentMovePolicy<T_ITEM>, class TComparePolicy = AkDefaultSortedKeyCompare<T_KEY>> AkForceInline bool AkSortedKeyArray< T_KEY, T_ITEM, U_POOL, U_KEY, TGrowBy, TMovePolicy, TComparePolicy >::Lesser (T_KEY & a, T_KEY & b) const inline
Definition at line 209 of file AkKeyArray.h.
Referenced by AkSortedKeyArray< T, T, ArrayPoolDefault, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::BinarySearch(), AkSortedKeyArray< T, T, ArrayPoolDefault, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::LowerBounds(), and AkSortedKeyArray< T, T, ArrayPoolDefault, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::Reorder().