AkLine::Intersect
AkLine
AkLine
Intersect
L
maxt
mint
P
PointAt
Intersect()
bool AkLine::Intersect (Ak3DVector A, Ak3DVector B) inline
Definition at line 1300 of file AkVectors.h.
References AkMax, AkMin, AKVECTORS_EPSILON, T3DVector< TDataType >::Cross(), T3DVector< AkReal32 >::Determinant(), L, T3DVector< TDataType >::L2_Norm(), T3DVector< TDataType >::LengthSquared(), maxt, mint, AKPLATFORM::OutputDebugMsg(), P, PointAt(), T3DVector< TDataType >::X, T3DVector< TDataType >::Y, and T3DVector< TDataType >::Z.
Referenced by AkPlane::FindIntersectionPoints().