AkFifoQueue::Enqueue
AkFifoQueue
Dequeue
Empty
Enqueue
Init
Term
~AkFifoQueue
Enqueue()
template<typename T , T TDEFAULT, class TAlloc = ArrayPoolDefault> AK_NODISCARD bool AkFifoQueue< T, TDEFAULT, TAlloc >::Enqueue (T in_value) inline
Enqueues the provided value. The value will be copied to the queue's internal buffer. Returns true if the enqueue was performed successfully. Returns false if the enqueue could not be performed. This can happen if the queue is "full", and some dequeue operations have to occur.
Definition at line 101 of file AkFifoQueue.h.
References AkAtomicCas64(), AkAtomicLoad64(), and AkAtomicStore64().