AkChannelConfig::HasLFE
AkChannelConfig
AkChannelConfig
Ambisonic
Anonymous
Clear
Deserialize
eConfigType
HasCenter
HasLFE
IsValid
Object
operator!=
operator!=
operator==
RemoveCenter
RemoveLFE
Serialize
SetAmbisonic
SetAnonymous
SetObject
SetSameAsMainMix
SetSameAsPassthrough
SetStandard
SetStandardOrAnonymous
Standard
uChannelMask
uNumChannels
HasLFE()
AkForceInline bool AkChannelConfig::HasLFE () const inline
Query if LFE channel is present.
Returns
True when LFE channel is present
Definition at line 687 of file AkSpeakerConfig.h.
References AK::HasLFE(), and uChannelMask.
Referenced by AkAudioFormat::HasLFE(), AkAudioBuffer::HasLFE(), and AkAudioBuffer::StandardToPipelineIndex().